services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4:8.1
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
