services:
  postgres:
    image: postgres:17.0-alpine3.20
    restart: always
    volumes:
      - postgres:${PGDATA}
    env_file:
      - .env
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U typeorm"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Will be accessible on port 80 unline the default compose file!
  pgAdmin:
    image: dpage/pgadmin4:8.4
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    network_mode: host
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ./configs/servers.config.json:/pgadmin4/servers.json
      - ./configs/preferences.config.json:/pgadmin4/preferences.json

volumes:
  postgres:
  pgadmin:
