version: "3.7"

services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
    network_mode: host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U typeorm"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4:6.5
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    network_mode: host

volumes:
  postgres:
