version: "3.7"

services:
  mongo:
    image: mongo:4.4.14-rc0-focal
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_volume:/data/db
    env_file:
      - .mongodb.env
    restart: always

volumes:
  mongodb_volume:
