services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    environment:
      LOG_LEVEL: DEBUG
      ENV: dev
    user: "${MY_UID:-1000}:${MY_GID:-1000}"
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src
