version: "3.8"

services:
  mongo:
    image: mongo:3.6.21
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: 123456789
    dns:
      hostname: "mongo"
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "27017:27017"
    networks:
      - mongo_net
  mongo-express:
    image: mongo-express:0.54.0
    depends_on:
      - mongo
    dns:
      hostname: "mongo-express"
    environments:
      - ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
      - ME_CONFIG_MONGODB_SERVER: "mogo"
      - ME_CONFIG_BASICAUTH_USERNAME: "root"
      - ME_CONFIG_BASICAUTH_PASSWORD: "123456789"
      - ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      - ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
      - ME_CONFIG_MONGODB_ADMINPASSWORD: "123456789"
      - ME_CONFIG_MONGODB_PORT: 27017
      - ME_CONFIG_MONGODB_SERVER: "mongo"
      - ME_CONFIG_REQUEST_SIZE: "100kb"
      - ME_CONFIG_SITE_BASEURL: "/"
      - ME_CONFIG_SITE_COOKIESECRET: "cookiesecret"
      - ME_CONFIG_SITE_SESSIONSECRET: "sessionsecret"
      - ME_CONFIG_SITE_SSL_ENABLED: "false"
      - ME_CONFIG_SITE_SSL_CRT_PATH: ""
      - ME_CONFIG_SITE_SSL_KEY_PATH: ""
    deploy:
      replicas: 1
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "8081:8081"
    networks:
      - mongo_net
networks:
  mongo_net:
    driver: overlay
