version: "3.7"

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgAdmin:
    image: dpage/pgadmin4:6.5
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
