version: "3.7"

services:
  postgres:
    image: postgres:13
    restart: always
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .env

  pgAdmin:
    image: dpage/pgadmin4:8.1
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "${PGADMIN_EXPOSED_PORT}:80"
