services:
  rabbitmq:
    image: rabbitmq:3.9.20-management-alpine
    env_file:
      - .rabbitmq.env
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbitmq:/var/lib/postgresql/data
    healthcheck:
      test: python3 -c "import urllib.request, sys; sys.exit(urllib.request.urlopen('http://localhost:15672').status != 200)"
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  rabbitmq:
