version: "3"

services:
  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: change-me
    container_name: rabbitmq
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:15672"]
#      interval: 30s
#      timeout: 10s
#      retries: 5

