version: "3.7"

services:
  elasticsearch:
    image: "${CREATED_IMAGE_NAME_PREFIX}:1"
    container_name: elasticsearch
    env_file:
      - ./.env
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ELASTIC_VERSION: $ELASTIC_VERSION
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
      http.cors.enabled: "true"
      http.cors.allow-credentials: "true"
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
    hostname: elasticsearch
    ports:
      - "${ELASTIC_EXPOSED_PORT1}:$ELASTIC_PORT1"
      - "$ELASTIC_EXPOSED_PORT2:${ELASTIC_PORT2}"
    volumes:
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data

volumes:
  elasticsearch_data:
