services:
  redis:
    image: redis:8.6-alpine3.23
    restart: always
    # command: >
    #   sh -c "redis-server
    #   --maxmemory $${REDIS_MAXMEMORY:-512mb}
    #   --maxmemory-policy $${REDIS_MAXMEMORY_POLICY:-allkeys-lfu}
    #   $${REDIS_PASSWORD:+--requirepass $$REDIS_PASSWORD}"
    ports:
      - 7000:${REDIS_PORT_NUMBER}
    env_file:
      - ./.env
    # deploy:
    #   resources:
    #     limits:
    #       memory: 640M
    healthcheck:
      test: >
        sh -c 'if [ -n "$$REDIS_PASSWORD" ]; then
          redis-cli -a "$$REDIS_PASSWORD" ping | grep PONG;
        else
          redis-cli ping | grep PONG;
        fi'
      interval: 5s
      timeout: 3s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    restart: always
    ports:
      - 5540:5540
    depends_on:
      redis:
        condition: service_healthy
    environment:
      RI_APP_PORT: 5540
      RI_LOG_LEVEL: debug
      RI_ACCEPT_TERMS_AND_CONDITIONS: true
      # 👇 Create a DB connection.
      RI_REDIS_HOST: redis
      RI_REDIS_PORT: 6379
      RI_REDIS_ALIAS: "Local Redis (compose)"
      RI_REDIS_USERNAME: default
      RI_REDIS_PASSWORD: "${REDIS_PASSWORD:-}"
    healthcheck:
      test: [
          "CMD-SHELL",
          "node",
          "--experimental-default-type=module",
          '-e "console.log((await fetch(''http://localhost:5540/api/health/'')).ok =
          == true && ''healthy'')"',
        ]
      interval: 5s
      timeout: 3s
      retries: 5
