version: "3"

services:
  pgadmin4:
    image: dpage/pgadmin4:6.21
    ports:
      - 9000:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRESQL_PASSWORD}

  postgres:
    image: bitnami/postgresql:15.2.0-debian-11-r13
    restart: always
    environment:
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    volumes:
      - postgres_volume:/bitnami/postgresql

volumes:
  postgres_volume:
