version: "3"

services:
  db:
    image: postgres:12.14
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: ${POSTGRES_USER} # instead of `-U postgres` in healthcheck
    # restart: always
    # networks:
    #   - db_net
    # volumes:
    #   - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      cluster.name: fusionauth
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "--fail",
          "--write-out",
          "'HTTP %{http_code}'",
          "--silent",
          "--output",
          "/dev/null",
          "http://localhost:9200/",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    # restart: unless-stopped
    # networks:
    #   - search_net
    # volumes:
    #   - search_data:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

  fusionauth:
    image: fusionauth/fusionauth-app:1.45.3
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/fusionauth
      DATABASE_ROOT_USERNAME: ${POSTGRES_USER}
      DATABASE_ROOT_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_USERNAME: fusionauth # IDK why but it seems that I cannot change this and it might be related to DATABASE_URL
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: 512M
      FUSIONAUTH_APP_KICKSTART_FILE: /usr/local/fusionauth/kickstart/kickstart.json
      FUSIONAUTH_APP_RUNTIME_MODE: development
      FUSIONAUTH_APP_URL: http://fusionauth:9012
      SEARCH_SERVERS: http://search:9200
      SEARCH_TYPE: elasticsearch
    ports:
      - 9012:9011
    # restart: unless-stopped
    # networks:
    #   - db_net
    #   - search_net
    volumes:
      - ./kickstart:/usr/local/fusionauth/kickstart
      # - fusionauth_config:/usr/local/fusionauth/config
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9012/api/status"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailcatcher:
    image: sj26/mailcatcher:v0.8.2
    ports:
      - "1021:1025"
      - "1081:1080"
# networks:
#   db_net:
#     driver: bridge
#   search_net:
#     driver: bridge
# volumes:
#   db_data:
#   fusionauth_config:
#   search_data:
