services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    depends_on:
      zookeeper:
        condition: service_healthy
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jaas.conf:/app/config/jaas.conf
    healthcheck:
      test:
        ["CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181"]
      interval: 30s
      timeout: 30s
      retries: 4

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    healthcheck:
      test: ["CMD-SHELL", "echo ruok | nc -w 2 zookeeper 2181"]
      interval: 5s
      timeout: 10s
      retries: 3

  kafka-manager:
    build: .
    depends_on:
      kafka:
        condition: service_healthy
      zookeeper:
        condition: service_healthy
