services:
  kafka:
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - 9092:9092
    depends_on:
      zookeeper:
        condition: service_started
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jaas.conf:/app/config/jaas.conf

  zookeeper:
    image: wurstmeister/zookeeper
    hostname: zookeeper
    ports:
      - 2181:2181
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  kafka-manager:
    build: .
    depends_on:
      kafka:
        condition: service_started
      zookeeper:
        condition: service_started
