services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio:/data
    env_file:
      - .env
    command: server --console-address ":9001" /data

volumes:
  minio:
