version: "3.7"

services:
  wordpress:
    image: wordpress:5.4
    hostname: wordpress
    container_name: wordpress
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: "wordpress"
      WORDPRESS_DB_PASSWORD: "password"
      WORDPRESS_DB_NAME: "wordpress"
    volumes:
      - wordpress:/var/www/html
    restart: always
    depends_on:
      - db

  db:
    image: mysql:5.7
    hostname: mysql-wordpress
    container_name: mysql-wordpress
    volumes:
      - db:/var/lib/mysql
    # ports:
    #     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root-password"
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: "wordpress"
      MYSQL_PASSWORD: "password"
      restart: always

volumes:
  wordpress: {}
  db: {}
