version: "3.7"

services:
  elasticsearch:
    image: "${CREATED_IMAGE_NAME_PREFIX}:1"
    build:
      context: ./elasticsearch
      args:
        EFK_VERSION: $EFK_VERSION
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
    hostname: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch_data
        target: /usr/share/elasticsearch/data
    networks:
      - efk

  kibana:
    image: "${CREATED_IMAGE_NAME_PREFIX}:1"
    build:
      context: ./kibana
      args:
        EFK_VERSION: $EFK_VERSION
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    hostname: kibana
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    networks:
      - efk
    depends_on:
      - elasticsearch

  filebeat:
    image: "${CREATED_IMAGE_NAME_PREFIX}:1"
    build:
      context: filebeat
      args:
        EFK_VERSION: $EFK_VERSION
    user: root
    hostname: filebeat
    volumes:
      - type: bind
        source: ./filebeat/config/filebeat.yml
        target: /usr/share/filebeat/filebeat.yml
        read_only: true
      - /var/lib/docker:/var/lib/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - efk
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:

networks:
  efk:
    driver: bridge
