services:
  mockserver:
    image: mockserver/mockserver:5.15.0
    restart: on-failure:3
    ports:
      - 1080:1080
    # volumes:
    #   # chmod o+r $(pwd)/mockserver.properties
    #   - ./mockserver.properties:/config/mockserver.properties
