# Registers all the mocks and protobuf files in one go

services:
  mocked-services:
    image: tkpd/gripmock
    ports:
      - "4770:4770"
      - "4771:4771"
    volumes:
      - ./proto:/proto
      - ./mocks:/stub
    command: --stub=/stub /proto/sample.proto
