services:
  postgres:
    image: postgres:17.0-alpine3.20
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    restart: always
    ports:
      - "${POSTGRESQL_EXPOSED_PORT}:5432"
    env_file:
      - .postgresql.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres
    # volumes:
    #   - type: bind
    #     source: ./pgdata
    #     target: /var/lib/postgresql/data:z
    #     volume:
    #       nocopy: true

networks:
  postgres:
    driver: bridge
