version: '3.7'

services:
  postgres:
    image: postgres:13
    container_name: ${COMPOSE_PROJECT_NAME}-postgresql
    restart: always
    ports:
      - '${POSTGRESQL_EXPOSED_PORT}:5432'
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - .postgresql.env
    networks:
      - postgres
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data:z
        volume:
          nocopy: true

networks:
  postgres:
    driver: bridge
