services:
  restore:
    build:
      context: .
      network: host
      dockerfile: Dockerfile
      args:
        DUMP_MONGODB_URI: $DUMP_MONGODB_URI
        MONGODB_DATABASE: $MONGODB_DATABASE
        RESTORE_MONGODB_URI: $RESTORE_MONGODB_URI
    env_file: .env
